### PR TITLE
v0.4 Add Bluepill 5.1.1/Xcode 11.2 support

### PR DESCRIPTION
**Pull request by aoimasu**

### CODE REVIEW

**Review by reececomo — APPROVED** [review]

**Review by reececomo — CHANGES_REQUESTED** [review]
Pls verify the updated step works (by running bitrise test and/or manual test).

I think you should also update the default iOS version input to match the Xcode 11.2 default.

**Comment by aoimasu** [comment]
https://app.bitrise.io/build/636d426b7c4bb18b#?tab=log confirmed it works on bitrise

**Comment by reececomo** [comment]
@aoimasu Just quickly rebuilding with iOS 13.2.2 (the last one was still running iOS 12.4): https://app.bitrise.io/build/6ee732a0f719849c#?tab=log

Screen Shot 2019-11-23 at 11 12 32 am

If it's cool with you I'm going to bump the default iOS version to 13.2.2 for the step

**Review by reececomo — APPROVED** [review]
@aoimasu looking good 👍

**Comment by reececomo** [comment]
@aoimasu Just quickly rebuilding with iOS 13.2.2 (the last one was still running iOS 12.4): https://app.bitrise.io/build/6ee732a0f719849c#?tab=log

Screen Shot 2019-11-23 at 11 12 32 am

If it's cool with you I'm going to bump the default iOS version to 13.2.2 for the step

**Pull request merged**
